# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grind < Formula
  desc "Stoic quotes CLI — your daily philosophical grind"
  homepage "https://github.com/warike/grind"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/warike/grind/releases/download/v0.1.0/grind_0.1.0_darwin_amd64.tar.gz"
      sha256 "f348c5b4c7e7c1ee53774b107dfaa6498fadd51c5a341370a701b3c02c18e43c"

      define_method(:install) do
        bin.install "grind"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/warike/grind/releases/download/v0.1.0/grind_0.1.0_darwin_arm64.tar.gz"
      sha256 "1efd303254bb8c33cf32a870b1393bb075dad1245fbdd02f159c34ed9703c1d6"

      define_method(:install) do
        bin.install "grind"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/warike/grind/releases/download/v0.1.0/grind_0.1.0_linux_amd64.tar.gz"
      sha256 "9c986bb1d6656260c49fd154f319f2ec08f07875c0daadc5b0fa04263087df97"
      define_method(:install) do
        bin.install "grind"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/warike/grind/releases/download/v0.1.0/grind_0.1.0_linux_arm64.tar.gz"
      sha256 "09515b3f5bae89eefabdee7299202173cbfe36f7b3798e3487c1bbefe5cb4b2d"
      define_method(:install) do
        bin.install "grind"
      end
    end
  end
end
